### ISSUE TITLE
change type of success indicator from boolean to something else

### ISSUE THREAD

**Issue by felixkrohn** [tobiasdenzler/checkbot#41]
In order to initialise this variable with a value other than "true" or "false" on iinitialisation.
https://github.com/tobiasdenzler/checkbot/blob/af941f38375642863bc79084d29339ec1b559b45/cmd/server/checks.go#L78
The reason would be to be able to differ between checks that have not yet been run, and checks that ran unsuccessfully. Alternatively set the value to -1 or NaN on init?

**Comment by tobiasdenzler** [comment]
Fix #42
